// frontend/src/components/react/MemoCanvas.tsx
import { useState, useMemo, useRef, useEffect } from 'react';
import { solve } from '../../lib/solver';
import {
  CANVAS_W, CANVAS_H, MIN_SIZE, COLORS, TOOLS,
  detectNodes, buildFigures, getPoints, centerX, centerY, getHandles,
} from '../../lib/canvas-utils';
import type { Shape, CanvasNode, DragState } from '../../lib/types';

interface CanvasChangePayload {
  figures: ReturnType<typeof buildFigures>;
  nodes: CanvasNode[];
  solution: Record<number, number> | null;
}

interface Props {
  numberSet?: number[];
  initialShapes?: Shape[];
  onCanvasChange?: (payload: CanvasChangePayload) => void;
}

export default function MemoCanvas({ numberSet = [], initialShapes = [], onCanvasChange }: Props) {
  const [shapes, setShapes] = useState<Shape[]>(() => [...initialShapes]);
  const [tool, setTool] = useState('select');
  const [selId, setSelId] = useState<number | null>(null);
  const [drag, setDrag] = useState<DragState | null>(null);
  const [nodes, setNodes] = useState<CanvasNode[]>(() => detectNodes(initialShapes));
  const [result, setResult] = useState<{ hasSolution: boolean; solution?: Record<number, number>; message?: string } | null>(null);
  const [colorIdx, setColorIdx] = useState(0);
  const svgRef = useRef<SVGSVGElement>(null);

  // Sync initialShapes if they change (edit mode)
  useEffect(() => {
    if (initialShapes.length > 0) {
      setShapes([...initialShapes]);
      setNodes(detectNodes(initialShapes));
      setResult(null);
    }
  }, [initialShapes.length]);

  const liveShapes = useMemo<Shape[]>(() => {
    if (drag?.type === 'create' && drag.shape && drag.shape.w > MIN_SIZE && drag.shape.h > MIN_SIZE) {
      return [...shapes, drag.shape];
    }
    return shapes;
  }, [shapes, drag]);

  const liveNodes = useMemo<CanvasNode[]>(() => {
    if (drag?.type === 'create') return detectNodes(liveShapes);
    return nodes;
  }, [nodes, liveShapes, drag]);

  const sel = useMemo(() => shapes.find(s => s.id === selId), [shapes, selId]);
  const selNodes = useMemo(() => nodes.filter(n => n.shapeIds.includes(selId!)), [nodes, selId]);
  const exclusiveNodes = useMemo(() => nodes.filter(n => n.shapeIds.length === 1).length, [nodes]);
  const sharedNodes = useMemo(() => nodes.filter(n => n.shapeIds.length > 1).length, [nodes]);
  const solutionEntries = useMemo<[string, number][]>(() => {
    if (!result?.solution) return [];
    return Object.entries(result.solution) as [string, number][];
  }, [result]);

  function svgPt(e: React.MouseEvent): [number, number] {
    const r = svgRef.current!.getBoundingClientRect();
    return [e.clientX - r.left, e.clientY - r.top];
  }

  function refresh(sh: Shape[]) {
    const newNodes = detectNodes(sh);
    setNodes(newNodes);
    setResult(null);
    const figs = buildFigures(sh, newNodes);
    onCanvasChange?.({ figures: figs, nodes: newNodes, solution: null });
  }

  function onSvgDown(e: React.MouseEvent) {
    if (tool === 'select') { setSelId(null); return; }
    const [x, y] = svgPt(e);
    setDrag({
      type: 'create',
      start: [x, y],
      shape: {
        id: Date.now(), type: tool as Shape['type'],
        color: COLORS[colorIdx % COLORS.length],
        operacion: 'suma', target: 10,
        x, y, w: 0, h: 0,
      },
    });
  }

  function onShapeDown(e: React.MouseEvent, s: Shape) {
    e.stopPropagation();
    if (tool !== 'select') return;
    setSelId(s.id);
    const [mx, my] = svgPt(e);
    setDrag({ type: 'move', id: s.id, ox: mx - s.x, oy: my - s.y });
  }

  function onHandleDown(e: React.MouseEvent, s: Shape, corner: string) {
    e.stopPropagation();
    const [mx, my] = svgPt(e);
    setDrag({ type: 'resize', id: s.id, corner, mx0: mx, my0: my, ox: s.x, oy: s.y, ow: s.w, oh: s.h });
  }

  function onMove(e: React.MouseEvent) {
    if (!drag) return;
    const [mx, my] = svgPt(e);

    if (drag.type === 'create' && drag.start && drag.shape) {
      const x = Math.min(drag.start[0], mx), y = Math.min(drag.start[1], my);
      const w = Math.abs(mx - drag.start[0]), h = Math.abs(my - drag.start[1]);
      setDrag(d => d ? { ...d, shape: { ...d.shape!, x, y, w, h } } : d);
      return;
    }

    if (drag.type === 'move' && drag.id !== undefined) {
      setShapes(prev => prev.map(s => s.id === drag.id
        ? { ...s, x: mx - drag.ox!, y: my - drag.oy! } : s));
      return;
    }

    if (drag.type === 'resize' && drag.id !== undefined) {
      const ddx = mx - drag.mx0!, ddy = my - drag.my0!;
      setShapes(prev => prev.map(s => {
        if (s.id !== drag.id) return s;
        let { x, y, w, h } = { x: drag.ox!, y: drag.oy!, w: drag.ow!, h: drag.oh! };
        if (drag.corner === 'tl') { x += ddx; y += ddy; w -= ddx; h -= ddy; }
        if (drag.corner === 'tr') { y += ddy; w += ddx; h -= ddy; }
        if (drag.corner === 'br') { w += ddx; h += ddy; }
        if (drag.corner === 'bl') { x += ddx; w -= ddx; h += ddy; }
        return { ...s, x, y, w: Math.max(MIN_SIZE, w), h: Math.max(MIN_SIZE, h) };
      }));
    }
  }

  function onUp() {
    if (!drag) return;
    if (drag.type === 'create' && drag.shape) {
      if (drag.shape.w > MIN_SIZE && drag.shape.h > MIN_SIZE) {
        const ns = [...shapes, drag.shape];
        setShapes(ns);
        refresh(ns);
        setSelId(drag.shape.id);
        setColorIdx(c => c + 1);
      }
      setTool('select');
    }
    if (drag.type === 'move' || drag.type === 'resize') {
      refresh(shapes);
    }
    setDrag(null);
  }

  function deleteShape() {
    const ns = shapes.filter(s => s.id !== selId);
    setShapes(ns);
    refresh(ns);
    setSelId(null);
  }

  function setProp(field: string, value: string | number) {
    const ns = shapes.map(s => s.id === selId ? { ...s, [field]: value } : s);
    setShapes(ns);
    refresh(ns);
  }

  function verify() {
    const figs = buildFigures(shapes, nodes);
    if (!numberSet.length) {
      setResult({ hasSolution: false, message: 'Define el número de conjunto primero' });
      return;
    }
    if (!nodes.length) {
      setResult({ hasSolution: false, message: 'No hay intersecciones — superpón figuras para crear nodos' });
      return;
    }
    const r = solve(figs as Parameters<typeof solve>[0], numberSet);
    setResult(r);
    onCanvasChange?.({ figures: figs, nodes, solution: r.hasSolution ? r.solution : null });
  }

  return (
    <div className="memo-canvas-wrap">
      {/* Toolbar */}
      <div className="canvas-toolbar">
        <button className={`ctool${tool === 'select' ? ' active' : ''}`} onClick={() => setTool('select')}>↖ Seleccionar</button>
        <span className="ctool-sep" />
        {TOOLS.map(t => (
          <button key={t.id} className={`ctool${tool === t.id ? ' active' : ''}`}
            onClick={() => setTool(t.id)} title={t.label}>
            {t.icon} {t.label}
          </button>
        ))}
        {selId && (
          <>
            <span className="ctool-sep" />
            <button className="ctool danger" onClick={deleteShape}>🗑 Eliminar</button>
          </>
        )}
      </div>

      {/* Canvas body */}
      <div className="canvas-body">
        <svg ref={svgRef} width={CANVAS_W} height={CANVAS_H} className="memo-svg"
          onMouseDown={onSvgDown} onMouseMove={onMove} onMouseUp={onUp} onMouseLeave={onUp}
          style={{ cursor: tool === 'select' ? 'default' : 'crosshair' }}>
          <defs>
            <pattern id="cgrid" width="24" height="24" patternUnits="userSpaceOnUse">
              <path d="M 24 0 L 0 0 0 24" fill="none" stroke="#1e293b" strokeWidth={0.5} />
            </pattern>
          </defs>
          <rect width={CANVAS_W} height={CANVAS_H} fill="url(#cgrid)" rx={6} />

          {/* Shapes */}
          {liveShapes.map(s => (
            <g key={s.id}>
              {s.type === 'circulo' ? (
                <ellipse
                  cx={s.x + s.w / 2} cy={s.y + s.h / 2}
                  rx={s.w / 2} ry={s.h / 2}
                  fill={s.color + '28'} stroke={s.color}
                  strokeWidth={s.id === selId ? 3 : 2}
                  strokeDasharray={s.id === selId ? '8 4' : undefined}
                  style={{ cursor: 'move', userSelect: 'none' }}
                  onMouseDown={e => onShapeDown(e, s)}
                />
              ) : (
                <polygon
                  points={getPoints(s)}
                  fill={s.color + '28'} stroke={s.color}
                  strokeWidth={s.id === selId ? 3 : 2}
                  strokeDasharray={s.id === selId ? '8 4' : undefined}
                  style={{ cursor: 'move', userSelect: 'none' }}
                  onMouseDown={e => onShapeDown(e, s)}
                />
              )}
              <g style={{ pointerEvents: 'none' }}>
                <rect x={centerX(s) - 20} y={centerY(s) - 10} width={40} height={20} rx={4}
                  fill="#0f172a" fillOpacity={0.7} />
                <text x={centerX(s)} y={centerY(s)} textAnchor="middle" dominantBaseline="middle"
                  fontSize={11} fill={s.color} fontWeight={600}>
                  {s.operacion === 'suma' ? 'Σ' : s.operacion === 'multiplicacion' ? '×' : '−'}={s.target}
                </text>
              </g>
            </g>
          ))}

          {/* Resize handles */}
          {sel && getHandles(sel).map(h => (
            <circle key={h.corner} cx={h.cx} cy={h.cy} r={7}
              fill="#0f172a" stroke="#38bdf8" strokeWidth={2}
              style={{ cursor: 'nwse-resize' }}
              onMouseDown={e => onHandleDown(e, sel, h.corner)} />
          ))}

          {/* Intersection nodes */}
          {liveNodes.map(n => (
            <g key={n.id} style={{ pointerEvents: 'none' }}>
              <circle cx={n.x} cy={n.y} r={14}
                fill={n.shapeIds.length > 1 ? '#78350f' : '#1e3a5f'}
                stroke={n.shapeIds.length > 1 ? '#fbbf24' : '#38bdf8'}
                strokeWidth={2.5} />
              <text x={n.x} y={n.y} textAnchor="middle" dominantBaseline="middle"
                fontSize={11} fontWeight="bold" fill="#fff">{n.id}</text>
            </g>
          ))}
        </svg>

        {/* Properties panel */}
        <div className="canvas-panel">
          {sel ? (
            <div className="panel-props">
              <div className="panel-title">
                Figura {shapes.findIndex(sh => sh.id === sel.id) + 1}
                <span className="panel-type-badge">{sel.type}</span>
              </div>
              <div className="panel-field">
                <label>Color</label>
                <input type="color" value={sel.color} onChange={e => setProp('color', e.target.value)} />
              </div>
              <div className="panel-field">
                <label>Operación</label>
                <select value={sel.operacion} onChange={e => setProp('operacion', e.target.value)}>
                  <option value="suma">Suma (Σ)</option>
                  <option value="resta">Resta (−)</option>
                  <option value="multiplicacion">Multiplicación (×)</option>
                </select>
              </div>
              <div className="panel-field">
                <label>Target (resultado esperado)</label>
                <input type="number" value={sel.target} onChange={e => setProp('target', +e.target.value)} />
              </div>
              <div className="panel-nodes-section">
                <label>Nodos de esta figura</label>
                {selNodes.length === 0 ? (
                  <p className="panel-no-nodes">Sin intersecciones aún — superpón otra figura</p>
                ) : (
                  <div className="panel-node-chips">
                    {selNodes.map(n => (
                      <span key={n.id} className={`nchip ${n.shapeIds.length > 1 ? 'shared' : 'solo'}`}>
                        N{n.id} {n.shapeIds.length > 1 ? '🟡' : '🔵'}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div className="panel-empty">
              <div className="panel-hint">
                <div className="hint-step"><span>Elige una figura y arrastra en el canvas para crearla</span></div>
                <div className="hint-step"><span>Superpón figuras — las intersecciones se detectan automáticamente</span></div>
                <div className="hint-step"><span>Selecciona una figura para editar propiedades</span></div>
                <div className="hint-step"><span>Arrastra las esquinas <b>azules</b> para redimensionar</span></div>
                <div className="hint-step"><span>Verifica si existe solución antes de guardar</span></div>
              </div>
            </div>
          )}

          <div className="panel-footer">
            {nodes.length > 0 && (
              <div className="nodes-summary">
                <span>🔵 {exclusiveNodes} exclusivos</span>
                <span>🟡 {sharedNodes} compartidos</span>
              </div>
            )}
            <button className="btn btn-full" onClick={verify}
              disabled={!shapes.length || !numberSet.length}
              style={{ marginTop: '.5rem' }}>
              🔍 Verificar Solución
            </button>
            {!numberSet.length && shapes.length > 0 && (
              <p className="panel-warn">⚠️ Define el número de conjunto arriba para poder verificar</p>
            )}
            {result && (
              <div className={`solver-badge ${result.hasSolution ? 'ok' : 'fail'}`}>
                {result.hasSolution ? (
                  <>
                    <div className="solver-ok-title">Solución válida encontrada</div>
                    <div className="sol-detail">
                      {solutionEntries.map(([k, v]) => (
                        <span key={k} className="sol-entry">N{k}={v}</span>
                      ))}
                    </div>
                    <div className="solver-ok-sub">El memoreto se puede guardar ↑</div>
                  </>
                ) : (
                  <span>{result.message || 'Sin solución con el número de conjunto actual — ajusta los targets o el número de conjunto'}</span>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Legend */}
      <div className="canvas-legend">
        <span><span className="leg-dot blue" />Nodo exclusivo</span>
        <span><span className="leg-dot gold" />Nodo compartido (intersección)</span>
        <span style={{ marginLeft: 'auto', color: '#475569', fontSize: '.75rem' }}>
          {shapes.length} figura{shapes.length !== 1 ? 's' : ''} · {nodes.length} nodo{nodes.length !== 1 ? 's' : ''}
        </span>
      </div>
    </div>
  );
}

// frontend/src/app/components/memo-canvas/memo-canvas.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnChanges, ViewChild, ElementRef, SimpleChanges } from '@angular/core';
import { solve } from '../../utils/solver';

const W = 560;
const H = 390;
const MERGE_DIST = 15;
const MIN_SIZE = 40;

const COLORS = ['#8B5CF6', '#06B6D4', '#EF4444', '#10B981', '#F59E0B', '#EC4899', '#F97316', '#14B8A6'];

const TOOLS = [
  { id: 'triangulo', icon: '▲', label: 'Triángulo' },
  { id: 'rectangulo', icon: '▬', label: 'Rectángulo' },
  { id: 'circulo', icon: '◯', label: 'Círculo' },
  { id: 'pentagono', icon: '⬠', label: 'Pentágono' },
];

interface Shape {
  id: number;
  type: string;
  color: string;
  operacion: string;
  target: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

interface Node {
  id: number;
  x: number;
  y: number;
  shapeIds: number[];
}

interface DragState {
  type: 'create' | 'move' | 'resize';
  start?: [number, number];
  shape?: Shape;
  id?: number;
  ox?: number;
  oy?: number;
  corner?: string;
  mx0?: number;
  my0?: number;
  ow?: number;
  oh?: number;
}

function getVerts(s: Shape): [number, number][] {
  const { x, y, w, h, type } = s;
  if (type === 'triangulo') return [[x + w / 2, y], [x, y + h], [x + w, y + h]];
  if (type === 'rectangulo') return [[x, y], [x + w, y], [x + w, y + h], [x, y + h]];
  if (type === 'circulo') {
    const cx = x + w / 2, cy = y + h / 2;
    return Array.from({ length: 16 }, (_, i) => {
      const a = (i / 16) * Math.PI * 2;
      return [cx + (w / 2) * Math.cos(a), cy + (h / 2) * Math.sin(a)] as [number, number];
    });
  }
  if (type === 'pentagono') {
    const cx = x + w / 2, cy = y + h / 2, r = Math.min(w, h) / 2;
    return Array.from({ length: 5 }, (_, i) => {
      const a = (i / 5) * Math.PI * 2 - Math.PI / 2;
      return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as [number, number];
    });
  }
  return [[x, y], [x + w, y], [x + w, y + h], [x, y + h]];
}

function segIntersect(a1: [number,number], a2: [number,number], b1: [number,number], b2: [number,number]): [number,number] | null {
  const dx1 = a2[0]-a1[0], dy1 = a2[1]-a1[1];
  const dx2 = b2[0]-b1[0], dy2 = b2[1]-b1[1];
  const d = dx1*dy2 - dy1*dx2;
  if (Math.abs(d) < 1e-8) return null;
  const t = ((b1[0]-a1[0])*dy2 - (b1[1]-a1[1])*dx2) / d;
  const u = ((b1[0]-a1[0])*dy1 - (b1[1]-a1[1])*dx1) / d;
  if (t > 0.005 && t < 0.995 && u > 0.005 && u < 0.995)
    return [a1[0]+t*dx1, a1[1]+t*dy1];
  return null;
}

function detectNodes(shapes: Shape[]): Node[] {
  const nodes: Node[] = [];
  let nid = 1;

  const addOrMerge = (x: number, y: number, ...ids: number[]) => {
    const ex = nodes.find(n => Math.hypot(n.x - x, n.y - y) < MERGE_DIST);
    if (ex) {
      ids.forEach(id => { if (!ex.shapeIds.includes(id)) ex.shapeIds.push(id); });
    } else {
      nodes.push({ id: nid++, x: Math.round(x), y: Math.round(y), shapeIds: [...ids] });
    }
  };

  for (let i = 0; i < shapes.length; i++) {
    const va = getVerts(shapes[i]);
    const ea = va.map((v, k) => [v, va[(k + 1) % va.length]] as [[number,number],[number,number]]);
    for (let j = i + 1; j < shapes.length; j++) {
      const vb = getVerts(shapes[j]);
      const eb = vb.map((v, k) => [v, vb[(k + 1) % vb.length]] as [[number,number],[number,number]]);
      ea.forEach(([a1, a2]) =>
        eb.forEach(([b1, b2]) => {
          const pt = segIntersect(a1, a2, b1, b2);
          if (pt) addOrMerge(pt[0], pt[1], shapes[i].id, shapes[j].id);
        })
      );
    }
  }
  return nodes;
}

function buildFigures(shapes: Shape[], nodes: Node[]) {
  return shapes.map((s, idx) => ({
    id: idx + 1,
    type: s.type,
    color: s.color,
    operacion: s.operacion,
    target: s.target,
    nodos: nodes.filter(n => n.shapeIds.includes(s.id)).map(n => n.id),
    _geo: { x: Math.round(s.x), y: Math.round(s.y), w: Math.round(s.w), h: Math.round(s.h) },
  }));
}

export function figuraToShapes(figuras: any[]): Shape[] {
  return figuras
    .filter(f => f._geo)
    .map(f => ({
      id: f.id,
      type: f.type,
      color: f.color,
      operacion: f.operacion,
      target: f.target,
      ...f._geo,
    }));
}

@Component({
  selector: 'app-memo-canvas',
  imports: [],
  template: `
    <div class="memo-canvas-wrap">
      <!-- Toolbar -->
      <div class="canvas-toolbar">
        <button class="ctool" [class.active]="tool === 'select'" (click)="tool = 'select'">↖ Seleccionar</button>
        <span class="ctool-sep"></span>
        @for (t of tools; track t.id) {
          <button class="ctool" [class.active]="tool === t.id" (click)="tool = t.id" [title]="t.label">
            {{ t.icon }} {{ t.label }}
          </button>
        }
        @if (selId) {
          <span class="ctool-sep"></span>
          <button class="ctool danger" (click)="deleteShape()">🗑 Eliminar</button>
        }
      </div>

      <!-- Canvas body -->
      <div class="canvas-body">
        <svg #svgEl [attr.width]="W" [attr.height]="H" class="memo-svg"
          (mousedown)="onSvgDown($event)"
          (mousemove)="onMove($event)"
          (mouseup)="onUp()"
          (mouseleave)="onUp()"
          [style.cursor]="tool === 'select' ? 'default' : 'crosshair'">

          <defs>
            <pattern id="cgrid" width="24" height="24" patternUnits="userSpaceOnUse">
              <path d="M 24 0 L 0 0 0 24" fill="none" stroke="#1e293b" stroke-width="0.5" />
            </pattern>
          </defs>
          <rect [attr.width]="W" [attr.height]="H" fill="url(#cgrid)" rx="6" />

          <!-- Shapes -->
          @for (s of liveShapes; track s.id) {
            @if (s.type === 'circulo') {
              <ellipse
                [attr.cx]="s.x + s.w/2" [attr.cy]="s.y + s.h/2"
                [attr.rx]="s.w/2" [attr.ry]="s.h/2"
                [attr.fill]="s.color + '28'"
                [attr.stroke]="s.color"
                [attr.stroke-width]="s.id === selId ? 3 : 2"
                [attr.stroke-dasharray]="s.id === selId ? '8 4' : null"
                style="cursor:move;user-select:none"
                (mousedown)="onShapeDown($event, s)"
              />
            } @else {
              <polygon
                [attr.points]="getPoints(s)"
                [attr.fill]="s.color + '28'"
                [attr.stroke]="s.color"
                [attr.stroke-width]="s.id === selId ? 3 : 2"
                [attr.stroke-dasharray]="s.id === selId ? '8 4' : null"
                style="cursor:move;user-select:none"
                (mousedown)="onShapeDown($event, s)"
              />
            }
            <!-- Label -->
            <g style="pointer-events:none">
              <rect
                [attr.x]="centerX(s) - 20" [attr.y]="centerY(s) - 10"
                width="40" height="20" rx="4" fill="#0f172a" fill-opacity="0.7"
              />
              <text
                [attr.x]="centerX(s)" [attr.y]="centerY(s)"
                text-anchor="middle" dominant-baseline="middle"
                font-size="11" [attr.fill]="s.color" font-weight="600">
                {{ s.operacion === 'suma' ? 'Σ' : s.operacion === 'multiplicacion' ? '×' : '−' }}={{ s.target }}
              </text>
            </g>
          }

          <!-- Resize handles for selected shape -->
          @if (sel) {
            @for (h of getHandles(sel); track h.corner) {
              <circle
                [attr.cx]="h.cx" [attr.cy]="h.cy" r="7"
                fill="#0f172a" stroke="#38bdf8" stroke-width="2"
                style="cursor:nwse-resize"
                (mousedown)="onHandleDown($event, sel, h.corner)"
              />
            }
          }

          <!-- Intersection nodes -->
          @for (n of liveNodes; track n.id) {
            <g style="pointer-events:none">
              <circle
                [attr.cx]="n.x" [attr.cy]="n.y" r="14"
                [attr.fill]="n.shapeIds.length > 1 ? '#78350f' : '#1e3a5f'"
                [attr.stroke]="n.shapeIds.length > 1 ? '#fbbf24' : '#38bdf8'"
                stroke-width="2.5"
              />
              <text [attr.x]="n.x" [attr.y]="n.y" text-anchor="middle" dominant-baseline="middle"
                font-size="11" font-weight="bold" fill="#fff">{{ n.id }}</text>
            </g>
          }
        </svg>

        <!-- Properties panel -->
        <div class="canvas-panel">
          @if (sel) {
            <div class="panel-props">
              <div class="panel-title">
                Figura {{ shapeIndex(sel) + 1 }}
                <span class="panel-type-badge">{{ sel.type }}</span>
              </div>
              <div class="panel-field">
                <label>Color</label>
                <input type="color" [value]="sel.color" (input)="setProp('color', $any($event.target).value)" />
              </div>
              <div class="panel-field">
                <label>Operación</label>
                <select [value]="sel.operacion" (change)="setProp('operacion', $any($event.target).value)">
                  <option value="suma">Suma (Σ)</option>
                  <option value="resta">Resta (−)</option>
                  <option value="multiplicacion">Multiplicación (×)</option>
                </select>
              </div>
              <div class="panel-field">
                <label>Target (resultado esperado)</label>
                <input type="number" [value]="sel.target" (input)="setProp('target', +$any($event.target).value)" />
              </div>
              <div class="panel-nodes-section">
                <label>Nodos de esta figura</label>
                @if (selNodes.length === 0) {
                  <p class="panel-no-nodes">Sin intersecciones aún — superpón otra figura</p>
                } @else {
                  <div class="panel-node-chips">
                    @for (n of selNodes; track n.id) {
                      <span class="nchip" [class.shared]="n.shapeIds.length > 1" [class.solo]="n.shapeIds.length === 1">
                        N{{ n.id }} {{ n.shapeIds.length > 1 ? '🟡' : '🔵' }}
                      </span>
                    }
                  </div>
                }
              </div>
            </div>
          } @else {
            <div class="panel-empty">
              <div class="panel-hint">
                <div class="hint-step"><span>Elige una figura y arrastra en el canvas para crearla</span></div>
                <div class="hint-step"><span>Superpón figuras — las intersecciones se detectan automáticamente</span></div>
                <div class="hint-step"><span>Selecciona una figura para editar propiedades</span></div>
                <div class="hint-step"><span>Arrastra las esquinas <b>azules</b> para redimensionar</span></div>
                <div class="hint-step"><span>Verifica si existe solución antes de guardar</span></div>
              </div>
            </div>
          }

          <div class="panel-footer">
            @if (nodes.length > 0) {
              <div class="nodes-summary">
                <span>🔵 {{ exclusiveNodes }} exclusivos</span>
                <span>🟡 {{ sharedNodes }} compartidos</span>
              </div>
            }
            <button class="btn btn-full" (click)="verify()" [disabled]="!shapes.length || !numberSet.length" style="margin-top:.5rem">
              🔍 Verificar Solución
            </button>
            @if (!numberSet.length && shapes.length > 0) {
              <p class="panel-warn">⚠️ Define el número de conjunto arriba para poder verificar</p>
            }
            @if (result) {
              <div class="solver-badge" [class.ok]="result.hasSolution" [class.fail]="!result.hasSolution">
                @if (result.hasSolution) {
                  <div class="solver-ok-title">Solución válida encontrada</div>
                  <div class="sol-detail">
                    @for (entry of solutionEntries; track entry[0]) {
                      <span class="sol-entry">N{{ entry[0] }}={{ entry[1] }}</span>
                    }
                  </div>
                  <div class="solver-ok-sub">El memoreto se puede guardar ↑</div>
                } @else {
                  <span>{{ result.message || 'Sin solución con el número de conjunto actual — ajusta los targets o el número de conjunto' }}</span>
                }
              </div>
            }
          </div>
        </div>
      </div>

      <!-- Legend -->
      <div class="canvas-legend">
        <span><span class="leg-dot blue"></span>Nodo exclusivo</span>
        <span><span class="leg-dot gold"></span>Nodo compartido (intersección)</span>
        <span style="margin-left:auto;color:#475569;font-size:.75rem">
          {{ shapes.length }} figura{{ shapes.length !== 1 ? 's' : '' }} · {{ nodes.length }} nodo{{ nodes.length !== 1 ? 's' : '' }}
        </span>
      </div>
    </div>
  `,
})
export class MemoCanvasComponent implements OnInit, OnChanges {
  @Input() numberSet: number[] = [];
  @Input() initialShapes: Shape[] = [];
  @Output() canvasChange = new EventEmitter<{ figures: any[], nodes: Node[], solution: any }>();

  @ViewChild('svgEl') svgElRef!: ElementRef<SVGSVGElement>;

  W = W; H = H;
  tools = TOOLS;

  shapes: Shape[] = [];
  tool = 'select';
  selId: number | null = null;
  drag: DragState | null = null;
  nodes: Node[] = [];
  result: any = null;
  colorIdx = 0;

  ngOnInit() {
    this.shapes = [...this.initialShapes];
    this.nodes = detectNodes(this.shapes);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['initialShapes'] && !changes['initialShapes'].firstChange) {
      this.shapes = [...this.initialShapes];
      this.nodes = detectNodes(this.shapes);
      this.result = null;
    }
  }

  get liveShapes(): Shape[] {
    if (this.drag?.type === 'create' && this.drag.shape &&
        this.drag.shape.w > MIN_SIZE && this.drag.shape.h > MIN_SIZE) {
      return [...this.shapes, this.drag.shape];
    }
    return this.shapes;
  }

  get liveNodes(): Node[] {
    if (this.drag?.type === 'create') {
      return detectNodes(this.liveShapes);
    }
    return this.nodes;
  }

  get sel(): Shape | undefined {
    return this.shapes.find(s => s.id === this.selId);
  }

  get selNodes(): Node[] {
    return this.nodes.filter(n => n.shapeIds.includes(this.selId!));
  }

  get exclusiveNodes(): number {
    return this.nodes.filter(n => n.shapeIds.length === 1).length;
  }

  get sharedNodes(): number {
    return this.nodes.filter(n => n.shapeIds.length > 1).length;
  }

  get solutionEntries(): [string, number][] {
    if (!this.result?.solution) return [];
    return Object.entries(this.result.solution) as [string, number][];
  }

  private svgPt(e: MouseEvent): [number, number] {
    const r = this.svgElRef.nativeElement.getBoundingClientRect();
    return [e.clientX - r.left, e.clientY - r.top];
  }

  private refresh(sh: Shape[]) {
    this.nodes = detectNodes(sh);
    this.result = null;
    const figs = buildFigures(sh, this.nodes);
    this.canvasChange.emit({ figures: figs, nodes: this.nodes, solution: null });
  }

  onSvgDown(e: MouseEvent) {
    if (this.tool === 'select') { this.selId = null; return; }
    const [x, y] = this.svgPt(e);
    this.drag = {
      type: 'create',
      start: [x, y],
      shape: {
        id: Date.now(), type: this.tool,
        color: COLORS[this.colorIdx % COLORS.length],
        operacion: 'suma', target: 10,
        x, y, w: 0, h: 0,
      },
    };
  }

  onShapeDown(e: MouseEvent, s: Shape) {
    e.stopPropagation();
    if (this.tool !== 'select') return;
    this.selId = s.id;
    const [mx, my] = this.svgPt(e);
    this.drag = { type: 'move', id: s.id, ox: mx - s.x, oy: my - s.y };
  }

  onHandleDown(e: MouseEvent, s: Shape, corner: string) {
    e.stopPropagation();
    const [mx, my] = this.svgPt(e);
    this.drag = { type: 'resize', id: s.id, corner, mx0: mx, my0: my, ox: s.x, oy: s.y, ow: s.w, oh: s.h };
  }

  onMove(e: MouseEvent) {
    if (!this.drag) return;
    const [mx, my] = this.svgPt(e);

    if (this.drag.type === 'create' && this.drag.start && this.drag.shape) {
      const x = Math.min(this.drag.start[0], mx), y = Math.min(this.drag.start[1], my);
      const w = Math.abs(mx - this.drag.start[0]), h = Math.abs(my - this.drag.start[1]);
      this.drag = { ...this.drag, shape: { ...this.drag.shape, x, y, w, h } };
    }

    if (this.drag.type === 'move' && this.drag.id !== undefined) {
      this.shapes = this.shapes.map(s => s.id === this.drag!.id
        ? { ...s, x: mx - this.drag!.ox!, y: my - this.drag!.oy! } : s);
    }

    if (this.drag.type === 'resize' && this.drag.id !== undefined) {
      const dx = mx - this.drag.mx0!, dy = my - this.drag.my0!;
      this.shapes = this.shapes.map(s => {
        if (s.id !== this.drag!.id) return s;
        let { x, y, w, h } = { x: this.drag!.ox!, y: this.drag!.oy!, w: this.drag!.ow!, h: this.drag!.oh! };
        if (this.drag!.corner === 'tl') { x += dx; y += dy; w -= dx; h -= dy; }
        if (this.drag!.corner === 'tr') { y += dy; w += dx; h -= dy; }
        if (this.drag!.corner === 'br') { w += dx; h += dy; }
        if (this.drag!.corner === 'bl') { x += dx; w -= dx; h += dy; }
        return { ...s, x, y, w: Math.max(MIN_SIZE, w), h: Math.max(MIN_SIZE, h) };
      });
    }
  }

  onUp() {
    if (!this.drag) return;
    if (this.drag.type === 'create' && this.drag.shape) {
      if (this.drag.shape.w > MIN_SIZE && this.drag.shape.h > MIN_SIZE) {
        const ns = [...this.shapes, this.drag.shape];
        this.shapes = ns;
        this.refresh(ns);
        this.selId = this.drag.shape.id;
        this.colorIdx++;
      }
      this.tool = 'select';
    }
    if (this.drag.type === 'move' || this.drag.type === 'resize') {
      this.refresh(this.shapes);
    }
    this.drag = null;
  }

  deleteShape() {
    const ns = this.shapes.filter(s => s.id !== this.selId);
    this.shapes = ns;
    this.refresh(ns);
    this.selId = null;
  }

  setProp(field: string, value: any) {
    const ns = this.shapes.map(s => s.id === this.selId ? { ...s, [field]: value } : s);
    this.shapes = ns;
    this.refresh(ns);
  }

  verify() {
    const figs = buildFigures(this.shapes, this.nodes);
    if (!this.numberSet.length) {
      this.result = { hasSolution: false, message: 'Define el número de conjunto primero' };
      return;
    }
    if (!this.nodes.length) {
      this.result = { hasSolution: false, message: 'No hay intersecciones — superpón figuras para crear nodos' };
      return;
    }
    const r = solve(figs as any, this.numberSet);
    this.result = r;
    this.canvasChange.emit({ figures: figs, nodes: this.nodes, solution: r.hasSolution ? r.solution : null });
  }

  shapeIndex(s: Shape): number {
    return this.shapes.findIndex(sh => sh.id === s.id);
  }

  getPoints(s: Shape): string {
    return getVerts(s).map(v => v.join(',')).join(' ');
  }

  centerX(s: Shape): number {
    const vs = getVerts(s);
    return vs.reduce((a, v) => a + v[0], 0) / vs.length;
  }

  centerY(s: Shape): number {
    const vs = getVerts(s);
    return vs.reduce((a, v) => a + v[1], 0) / vs.length;
  }

  getHandles(s: Shape): { corner: string, cx: number, cy: number }[] {
    return [
      { corner: 'tl', cx: s.x, cy: s.y },
      { corner: 'tr', cx: s.x + s.w, cy: s.y },
      { corner: 'br', cx: s.x + s.w, cy: s.y + s.h },
      { corner: 'bl', cx: s.x, cy: s.y + s.h },
    ];
  }
}
