// frontend/src/components/react/GrupoDetalle.tsx
import { useState } from 'react';

interface Student { id: number; name: string; lastname: string; username: string; total_score: number; }
interface Memo { id: number; title: string; dificultad: string; }
interface Group { id: number; name: string; code: string; }

interface Props {
  groupId: string;
  initialGroup: Group;
  initialStudents: Student[];
  initialMemos: Memo[];
  allMemos: Memo[];
}

export default function GrupoDetalle({ groupId, initialGroup, initialStudents, initialMemos, allMemos }: Props) {
  const [tab, setTab] = useState<'personas' | 'tareas'>('personas');
  const [students] = useState<Student[]>(initialStudents);
  const [memos, setMemos] = useState<Memo[]>(initialMemos);
  const [selMemo, setSelMemo] = useState('');
  const [msg, setMsg] = useState('');

  const available = allMemos.filter(m => !memos.some(am => am.id === m.id));

  async function handleAssign() {
    if (!selMemo) return;
    const res = await fetch(`/api/proxy/groups/${groupId}/memoretos`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ memoreto_id: Number(selMemo) }),
    });
    const d = await res.json();
    setMsg(res.status === 201 ? 'Memoreto asignado' : (d.message || 'Error al asignar'));
    const assigned = allMemos.find(m => m.id === Number(selMemo));
    if (assigned && res.status === 201) {
      setMemos(prev => [...prev, assigned]);
      setSelMemo('');
    }
  }

  async function handleRemove(memoId: number) {
    await fetch(`/api/proxy/groups/${groupId}/memoretos/${memoId}`, {
      method: 'DELETE',
      credentials: 'include',
    });
    setMemos(prev => prev.filter(m => m.id !== memoId));
  }

  return (
    <div className="page-content" style={{ maxWidth: '800px' }}>
      <div>
        <div className="group-code-bar">
          <span>Código de acceso:</span>
          <span className="code-display">{initialGroup.code}</span>
        </div>

        <div className="dash-tabs" style={{ width: 'fit-content', marginBottom: '1.25rem' }}>
          <button className={tab === 'personas' ? 'active' : ''} onClick={() => setTab('personas')}>
            Personas ({students.length})
          </button>
          <button className={tab === 'tareas' ? 'active' : ''} onClick={() => setTab('tareas')}>
            Tareas ({memos.length})
          </button>
        </div>

        {tab === 'personas' && (
          <div className="card-list">
            {students.length === 0 ? (
              <p className="empty">Sin estudiantes. Comparte el código para que se unan.</p>
            ) : students.map(s => (
              <div key={s.id} className="simple-row">
                <span>{s.name} {s.lastname}</span>
                <span style={{ fontSize: '.78rem', color: 'var(--on-surface-variant)' }}>@{s.username}</span>
                <span style={{ fontSize: '.83rem', fontWeight: 700, color: 'var(--secondary)' }}>{s.total_score} pts</span>
              </div>
            ))}
          </div>
        )}

        {tab === 'tareas' && (
          <>
            <div className="assign-section">
              <h4>Asignar memoreto</h4>
              <div className="row" style={{ alignItems: 'flex-end' }}>
                <div className="field" style={{ flex: 1 }}>
                  <select value={selMemo} onChange={e => setSelMemo(e.target.value)}>
                    <option value="">Seleccionar...</option>
                    {available.map(m => (
                      <option key={m.id} value={m.id}>{m.title} ({m.dificultad})</option>
                    ))}
                  </select>
                </div>
                <button className="btn btn-sm" onClick={handleAssign} disabled={!selMemo}>Asignar</button>
              </div>
              {msg && <p className="hint">{msg}</p>}
            </div>

            <div className="card-list" style={{ marginTop: '.75rem' }}>
              {memos.length === 0 ? (
                <p className="empty">Sin memoretos asignados.</p>
              ) : memos.map(m => (
                <div key={m.id} className="simple-row">
                  <span>{m.title}</span>
                  <span className="badge small">{m.dificultad}</span>
                  <button className="btn btn-sm btn-danger" onClick={() => handleRemove(m.id)}>Quitar</button>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// frontend/src/app/pages/grupo-detalle/grupo-detalle.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-grupo-detalle',
  standalone: true,
  imports: [FormsModule],
  template: `
    @if (!group) {
      <p class="empty">Cargando...</p>
    } @else {
      <div class="page-content" style="max-width:800px">
        <div>
          <div class="group-code-bar">
            <span>Código de acceso:</span>
            <span class="code-display">{{ group.code }}</span>
          </div>

          <div class="dash-tabs" style="width:fit-content;margin-bottom:1.25rem">
            <button [class.active]="tab === 'personas'" (click)="setTab('personas')">
              Personas ({{ students.length }})
            </button>
            <button [class.active]="tab === 'tareas'" (click)="setTab('tareas')">
              Tareas ({{ memos.length }})
            </button>
          </div>

          @if (tab === 'personas') {
            <div class="card-list">
              @if (students.length === 0) {
                <p class="empty">Sin estudiantes. Comparte el código para que se unan.</p>
              } @else {
                @for (s of students; track s.id) {
                  <div class="simple-row">
                    <span>{{ s.name }} {{ s.lastname }}</span>
                    <span style="font-size:.78rem;color:var(--on-surface-variant)">&#64;{{ s.username }}</span>
                    <span style="font-size:.83rem;font-weight:700;color:var(--secondary)">{{ s.total_score }} pts</span>
                  </div>
                }
              }
            </div>
          }

          @if (tab === 'tareas') {
            <div class="assign-section">
              <h4>Asignar memoreto</h4>
              <div class="row" style="align-items:flex-end">
                <div class="field" style="flex:1">
                  <select [(ngModel)]="selMemo">
                    <option value="">Seleccionar...</option>
                    @for (m of available; track m.id) {
                      <option [value]="m.id">{{ m.title }} ({{ m.dificultad }})</option>
                    }
                  </select>
                </div>
                <button class="btn btn-sm" (click)="handleAssign()" [disabled]="!selMemo">Asignar</button>
              </div>
              @if (msg) { <p class="hint">{{ msg }}</p> }
            </div>

            <div class="card-list" style="margin-top:.75rem">
              @if (memos.length === 0) {
                <p class="empty">Sin memoretos asignados.</p>
              } @else {
                @for (m of memos; track m.id) {
                  <div class="simple-row">
                    <span>{{ m.title }}</span>
                    <span class="badge small">{{ m.dificultad }}</span>
                    <button class="btn btn-sm btn-danger" (click)="handleRemove(m.id)">Quitar</button>
                  </div>
                }
              }
            </div>
          }
        </div>
      </div>
    }
  `,
  styles: [`:host { display: block; }`],
})
export class GrupoDetalleComponent implements OnInit {
  id!: string;
  group: any = null;
  students: any[] = [];
  memos: any[] = [];
  allMemos: any[] = [];
  tab: 'personas' | 'tareas' = 'personas';
  selMemo = '';
  msg = '';

  constructor(private route: ActivatedRoute, private auth: AuthService, private api: ApiService, private cdr: ChangeDetectorRef) {}

  ngOnInit() {
    this.id = this.route.snapshot.paramMap.get('id')!;
    this.fetchData();
  }

  async fetchData() {
    try {
      const [g, st, mm, all] = await Promise.all([
        this.api.getGroup(this.id, this.auth.token),
        this.api.getGroupStudents(this.id, this.auth.token),
        this.api.getGroupMemoretos(this.id, this.auth.token),
        this.api.getMyMemoretos(this.auth.token),
      ]);
      this.group = g.data.group;
      this.students = st.data.students || [];
      this.memos = mm.data.memoretos || [];
      this.allMemos = all.data.memoretos || [];
    } catch (e) {
      console.error('grupo-detalle load error', e);
    } finally {
      this.cdr.detectChanges();
    }
  }

  get available(): any[] {
    return this.allMemos.filter(m => !this.memos.some(am => am.id === m.id));
  }

  setTab(t: 'personas' | 'tareas') { this.tab = t; this.cdr.detectChanges(); }

  async handleAssign() {
    if (!this.selMemo) return;
    const res = await this.api.assignMemoreto(this.id, Number(this.selMemo), this.auth.token);
    this.msg = res.status === 201 ? 'Memoreto asignado' : (res.data.message || 'Error al asignar');
    this.fetchData();
  }

  async handleRemove(memoId: number) {
    await this.api.removeMemoretoFromGroup(this.id, memoId, this.auth.token);
    this.fetchData();
  }
}
